repo_url: https://github.com/Requisitos-de-Software/2025.1-Carteira-Digital-de-Transito
repo_name: 2025.1-Carteira-Digital-de-Transito

site_name: e-GDF

nav:
  - Home: index.md
  - Apresentação: apresentacoes/apresentacao.md
  - Atas:
    - Ata 1: atas/ata01.md
    - Ata 2: atas/ata02.md
    - Ata 3: atas/ata03.md
    - Ata 5: atas/ata05.md
  - Pré-Rastreabilidade: 
    - Rich Picture: pre-rastreabilidade/rich_picture.md
  - Planejamento:
    - Aplicativos Selecionados: planejamento/aplicativos_selecionados.md
    - Aplicativo Escolhido: planejamento/app_selecionado.md
    - Ferramentas: planejamento/ferramentas.md
    - Heat Map: planejamento/heatmap.md
    - Cronograma: planejamento/cronograma.md
    - Metodologia: planejamento/metodologia.md
    - Termo de Uso: planejamento/termos_de_uso.md
  - Elicitação:
    - Técnicas:
      - Analise de Documentos: elicitacao/tec_elicitacao/analise_documentos.md
      - Brainstorming: elicitacao/tec_elicitacao/brainstorming.md
      - Entrevista: elicitacao/tec_elicitacao/entrevista.md
      - Introspecção: elicitacao/tec_elicitacao/introspeccao.md
    - Requisitos Elicitados: elicitacao/req_elicitados.md
  - Verificação:
     - Grupo:
        - Entrega 1:
              - Verificação Grupo 9: verificacao/grupo/entrega01/planejamento-verificacao.md
              - Verificação Próprio Grupo: verificacao/grupo/entrega01/inspecao.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Claro

  language: pt-BR
  favicon: assets/egdf_logo.png
  logo: assets/egdf_logo.png

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox:
      touchNavigation: true
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      caption_position: bottom